// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcm5VcFBrzm7OWT8XHMYsaKTydHVWRlAE',
    appId: '1:651090819534:web:1c69b78a4f098db520939f',
    messagingSenderId: '651090819534',
    projectId: 'pizza-delivery-2497c',
    authDomain: 'pizza-delivery-2497c.firebaseapp.com',
    storageBucket: 'pizza-delivery-2497c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99Q7op9de7gcXgfVhvzYSsfYnIJOpzTA',
    appId: '1:651090819534:android:6f973d380f83fd4b20939f',
    messagingSenderId: '651090819534',
    projectId: 'pizza-delivery-2497c',
    storageBucket: 'pizza-delivery-2497c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC61VftIabD47odw9CaFd1aM6MKDB0IUkk',
    appId: '1:651090819534:ios:5f9cca985e8bfe3120939f',
    messagingSenderId: '651090819534',
    projectId: 'pizza-delivery-2497c',
    storageBucket: 'pizza-delivery-2497c.appspot.com',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC61VftIabD47odw9CaFd1aM6MKDB0IUkk',
    appId: '1:651090819534:ios:9e418fc9004db7c720939f',
    messagingSenderId: '651090819534',
    projectId: 'pizza-delivery-2497c',
    storageBucket: 'pizza-delivery-2497c.appspot.com',
    iosBundleId: 'com.example.pizzaDeliveryApp.RunnerTests',
  );
}
